apiVersion: v1
kind: Service
metadata:
  name: decode-jwt-service
spec:
  # type: LoadBalancer
  # ports:
  #   - name: http
  #     port: 8089
  #     protocol: TCP
  #     targetPort: 8080
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  selector:
    app: decode-jwt
